###*
Auto generated by MySQL Workbench Schema Exporter.
Version 2.1.5-dev (node-sequelize) on 2014-12-08 18:35:25.
Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
information.
###
module.exports = (sequelize, DataTypes) ->
  sequelize.define "Entry",
    modified_on:
      type: DataTypes.DATE

    text:
      type: DataTypes.STRING

    id:
      type: DataTypes.INTEGER

    entry_title:
      type: DataTypes.STRING
  ,
    timestamps: false
    underscored: true
    tableName: "entry"
    syncOnAssociation: false

