###*
Auto generated by MySQL Workbench Schema Exporter.
Version 2.1.5-dev (node-sequelize) on 2014-12-08 18:35:25.
Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
information.
###
module.exports = (sequelize, DataTypes) ->
  sequelize.define "Subscription",
    id:
      type: DataTypes.INTEGER
      primaryKey: true
      autoIncrement: true

    is_group:
      type: DataTypes.INTEGER
      unique: "feedIndex"

    site_id:
      type: DataTypes.INTEGER
      unique: "feedIndex"

    retrieved_on:
      type: DataTypes.DATE

    title:
      type: DataTypes.STRING
  ,
    timestamps: false
    underscored: true
    tableName: "subscription"
    syncOnAssociation: false

